[[main]]
  name = "About"
  pageRef = "about"
  weight = 10
[[main]]
  name = "Research"
  pageRef = "research"
  weight = 20
[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 30
[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 40
[[main]]
  name = "Tutorials"
  pageRef = "tutorials"
  weight = 50
[[main]]
  name = "Join us"
  pageRef = "join"
  weight = 60
[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 70

[[footer]]
  name = "Publications"
  pageRef = "publications"
  weight = 10
[[footer]]
  name = "Join us"
  pageRef = "join"
  weight = 20
